SYMBOLS="TCS INFY RELIANCE HDFCBANK WIPRO ITC SBIN LT AXISBANK MARUTI ONGC SUNPHARMA TATASTEEL BAJFINANCE ASIANPAINT HCLTECH KOTAKBANK ULTRACEMCO NESTLEIND POWERGRID"

for sym in $SYMBOLS; do
  curl -s -o /dev/null http://localhost:3002/api/stock/$sym
  sleep 0.5
done
